### ISSUE TITLE
Session Token not Valid

### ISSUE THREAD

**Issue by Strobelix80** [orlopau/ds-wrapper#1]
Checking if session token is valid might not be working correctly. 
Console always prints: "requesting new session token..."
The script always generates a new session token and doesn't check if the old session token is still valid.

**Comment by orlopau** [comment]
I will look into it thanks for the report. :+1:

**Comment by Strobelix80** [comment]
Is it possible to get a response for a „lastCalledScene“-Request? 
How has the query to look like?
